apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: uqtoyhwnd-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-dc47c7deac.ejfx.p3.openshiftapps.com/rhtap/rhtap-qe:a09803d1d3f7362d647fff9b57f25039df3b1ddd@sha256:fd0909a499fdb708438bebe390af83b4dc9eb37fb33a67096cc225fa91eb9e17
          name: container-image
